name: Checks

on:
  push:
    branches:
      - master

jobs:
  build:
    name: FOSSA
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up GOPATH
        run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0

      - name: Build
        run: go build ./...

      - name: Analyze
        run: plz run ///pleasings2//tools/misc:fossa -- analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
